### ISSUE TITLE
Test on remote CDF connection

### ISSUE THREAD

**Issue by Mincelot** [dilevin/computer-graphics-shader-pipeline#12]
How do we test if our code compiles at run-time with SSH? Right now I'm getting this error when try to run the program:
GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable
Could not create glfw window

**Comment by WChrisK** [comment]
Unless you plan on doing some wizardry to get an offscreen headless OpenGL context, you are not getting a GL context without a window. Without a GL context, you aren't compiling your shaders. Thus, you're out of luck.

You're going to have to test these on your own computer, or CDF computers. If it works on your computer then it _probably_ works on CDF... however because each vendor provides their own compiler for glsl, it's technically possible that what works on one computer might be weird or broken on another. Unlikely, but it is possible.

One way around this would be to [connect remotely to a desktop on CDF](https://www.teach.cs.toronto.edu/using_cdf/remote_access_server.html), however if the computers there have archaic hardware (which I've already seen from someone having issues on A5) then you're not getting a viable GL context either. You might have to go to Bahen to the graphics computers and test it out if you want to make certain they are fine.

**Comment by Mincelot** [comment]
I was able to connect to CDF via remote desktop but it seems the GLX version is lower than the requirement for the assignment (1.2)? Is there anyway we can get around with this?

**Comment by rin-23** [comment]
you will probably have to use one the computers in bahen. I believe admins told us there is no way to choose what kind of hardware you will be running on when using remote desktop. Since the assignment only requires you to write shaders, you can work on your local machine and then test everything before submission on CDF and it should all work.

**Comment by Mincelot** [comment]
Do you happen to know which lab room in BA is usually not reserved for courses that we can use to test our code?

**Comment by WChrisK** [comment]
I don't remember the room number (sorry :( ...) but there are special reserved ones.

Here's some ASCII art, if you go to the `[HERE]` area there should be great computers... last time I checked that is (unless I remember wrong). It's this room behind these translucent panels on the south side of Bahen. Beside the computer labs you can look over the railing down to the Cube, which is on the same side of the hallway as the graphics computer room is. I hope I'm right but I'm not 100% sure!

```
     (Old?)CSSU    Cube              HelpRoom
           | |___________[HERE]____|
       Door   _____________________
           | |                     | CDF Labs
           | |______
|||Stairs|||
           |     Big open area with tables/chairs/etc
           | 
           |  
___________| |____________ 
__________________________
Usually tutorial rooms

          |
          |
          V
        North
```

**Comment by rin-23** [comment]
3rd floor labs are usually available later in the day (after 4 or 5). 
2nd floor labs might have outdated hardware.
