### ISSUE TITLE
Cannot run test-01.json

### ISSUE THREAD

**Issue by harrychy8** [dilevin/computer-graphics-shader-pipeline#2]
Tried to run the program using Powershell, a small black window popped up at the top left corner then nothing happens.
I am using Windows. Can someone help me?
Thank you!

**Comment by harrychy8** [comment]
There are not any error messages either

**Comment by rarora7777** [comment]
This is just a guess, but I think it's because the default executable path in VS is different from *NIX systems. The (relative) shader paths are hardcoded in the test files, and your program is unable to find them. Try changing the output path in VS from `/build/Release` to `/build`. A similar effect can be achieved by running `./Release/shaderpipeline.exe` from the `/build` folder.
