### ISSUE TITLE
Can we rescale improved_perlin_noise

### ISSUE THREAD

**Issue by milomg** [dilevin/computer-graphics-shader-pipeline#79]
At the top of improved perline noise there is a comment that says `// Values between  -½ and ½ ?`. This seems to happen if you take the exact code of perlin_noise and replace smooth_step with improved_smooth_step. Why does this happen, and can we multiply the results by two at the end to make the values between -1 and 1 instead?

**Comment by mengf821** [comment]
Hello, you don't need to do any additional things for that file outside of basically replacing `smooth_step` with `improved_smooth_step`. You do not need to multiply the results by 2.

**Comment by milomg** [comment]
Why are the values between  -½ and ½  for improved_perlin_noise but not for perlin_noise?

**Comment by mengf821** [comment]
I think the value actually won't be exactly between -1 and 1 for either of them. In fact, I'm not sure if they would be between -0.5 to 0.5. It's an optimization question that you can solve for and here is an interesting discussion on it https://www.gamedev.net/forums/topic/285533-2d-perlin-noise-gradient-noise-range--/

But overall you really don't need to worry about the range. When you use the noises for your bumps you can scale them however you like

**Comment by milomg** [comment]
Oh that source is interesting, and the derivation is cool! I wonder why the two files (perlin and improved perlin) in our code have different ranges though, because both should reach ±1 on the axes

Is it ok if our perlin noise functions applies some scaling to it's output? (My current code includes some scaling inside the improved perlin function, should I rewrite it to scale places where I call that function instead?)

**Comment by mengf821** [comment]
I'm not entirely sure what the range for the improved perlin noise in our implementation is. If you want to check out what the maximum/minimum value would be it might be a fun little thing to do with a symbolic toolkit. I appreciate that you pointed it out and I think it is possible that the code comment has a mistake. 

As for the functions, I would prefer that you do not add scaling to the output of th perlin noise function because we want to see the implementation of improved perlin noise without it (just like how they were presented to you in the textbook/slides). You can do whatever kind of scaling/adding different function together/etc. you want in `bump_height`. That and the plant should be the only place where `improved_perlin_noise` is called so I think moving it shouldn't be difficult

**Comment by milomg** [comment]
Thanks!
